language: objective-c
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator11.0
  - TVOS_SDK=appletvsimulator11.0
script:
  - xcodebuild -showsdks
  - xcodebuild -project Project/Player.xcodeproj -scheme 'Debug - iOS' -sdk $IOS_SDK build analyze
#  - xcodebuild -project Project/Player.xcodeproj -scheme 'Debug - tvOS' -sdk $TVOS_SDK build analyze
